apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    kubernetes.io/ingress.class: gce
    # Add to generate certificates for this ingress
    kubernetes.io/tls-acme: 'true'
spec:
  rules:
    - host: {{ .Values.fqdn }}
      http:
        paths:
          - backend:
              serviceName: {{ template "fullname" . }}-esp
              servicePort: {{ .Values.service.esp.portName }}
            path: /*
  tls:
    # With this configuration kube-lego will generate a secret in namespace foo called `example-tls`
    # for the URL `www.example.com`
    - hosts:
        - "{{ .Values.fqdn }}"
      secretName: {{ template "fullname" . }}-tls
